site:
  title: Teak Documentation
  url: https://docs.gocarrot-dev.com/
  start_page: sdk-reference::index.adoc
content:
  sources:

  ### Locally generated API Docs ###
  - url: ./../../teak-unity
    edit_url: false
    start_path: docs

  - url: ./../../teak-ios
    edit_url: false
    start_path: docs

  - url: ./../../teak-android
    edit_url: false
    start_path: docs

  ### Pretend API Docs ###
  # - url: https://github.com/GoCarrot/pretend-teak-api-docs.git
  #   edit_url: false
  #   start_path: unity

  # - url: https://github.com/GoCarrot/pretend-teak-api-docs.git
  #   edit_url: false
  #   start_path: ios

  # - url: https://github.com/GoCarrot/pretend-teak-api-docs.git
  #   edit_url: false
  #   start_path: android

  ### Local SDK Reference Docs ###
  - url: ./../../teak-sdk-reference
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
ui:
  bundle:
    # The first element of '.' is needed so that the rest of the path is evaluated from
    # the location of the playbook yml. This way it will work if invoked from either
    # the playbook path, or the project root path.
    url: ./../build/ui-bundle.zip
  supplemental_files: ./supplemental-ui

asciidoc:
  extensions:
  - ./lib/doxygen2adoc

  attributes:
    doxygen2adoc:
    - symbols:
      - ./../../teak-unity/docs/symbolMap.json
      - ./../../teak-android/docs/symbolMap.json
      - ./../../teak-ios/docs/symbolMap.json
      verbose: false
      strict: false
