site:
  title: Teak Documentation
  url: /
  start_page: home::index.adoc
content:
  sources:
  ### Home ###
  - url: ./../
    start_path: docs

  ### Locally generated SDK Docs ###
  - url: ./../../teak-unity
    edit_url: false
    start_path: docs

  - url: ./../../teak-ios
    edit_url: false
    start_path: docs

  - url: ./../../teak-android
    edit_url: false
    start_path: docs

  ### Local Server API Docs ###
  - url: ./../../server-api-docs

  ### Local Usage Docs ###
  - url: ./../../teak-usage
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
ui:
  bundle:
    # The first element of '.' is needed so that the rest of the path is evaluated from
    # the location of the playbook yml. This way it will work if invoked from either
    # the playbook path, or the project root path.
    url: ./../build/ui-bundle.zip
  supplemental_files: ./supplemental-ui

asciidoc:
  extensions:
  - ./lib/doxygen2adoc

  attributes:
    page-component-sort-order: 'home, usage, *'
    page-reference-sort-order: '!home, !usage, server-api, *'
    linkattrs: ''
    experimental: ''
    doxygen2adoc:
    - symbols:
      - ./../../teak-unity/docs/symbolMap.json
      - ./../../teak-android/docs/symbolMap.json
      - ./../../teak-ios/docs/symbolMap.json
      verbose: false
      strict: false
