site:
  title: Teak Documentation
  url: https://docs.gocarrot-dev.com/
  start_page: sdk-reference::index.adoc
content:
  sources:
  # iOS API
  - url: ./../../teak-ios
    edit_url: false
    start_path: docs
  # Android API
  - url: ./../../teak-android
    edit_url: false
    start_path: docs
  # Unity API
  - url: ./../../teak-unity
    edit_url: false
    start_path: docs
  # SDK usage docs
  - url: https://github.com/GoCarrot/teak-sdk-reference.git
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
ui:
  bundle:
    # The first element of '.' is needed so that the rest of the path is evaluated from
    # the location of the playbook yml. This way it will work if invoked from either
    # the playbook path, or the project root path.
    url: ./../build/ui-bundle.zip
  supplemental_files: ./supplemental-ui

asciidoc:
  extensions:
  - ./lib/doxygen2adoc

  attributes:
    doxygen2adoc:
    - symbols:
      - ./../../teak-unity/docs/symbolMap.json
      - ./../../teak-android/docs/symbolMap.json
      - ./../../teak-ios/docs/symbolMap.json
      verbose: false
      strict: false
