site:
  title: Teak Documentation
  url: https://docs.gocarrot-dev.com/
  start_page: ::index.adoc
  keys:
    fathom: 'OBJZLAOP'
urls:
  latest_version_segment_strategy: replace
  latest_version_segment: latest
content:
  sources:
  ### Home ###
  - url: ./../
    start_path: docs

  ### Locally generated SDK Docs ###
  - url: ./../../teak-unity
    edit_url: false
    start_path: docs

  - url: ./../../teak-ios
    edit_url: false
    start_path: docs

  - url: ./../../teak-android
    edit_url: false
    start_path: docs

  # SDK usage docs
  - url: https://github.com/GoCarrot/server-api-docs.git
  # Teak usage docs
  - url: https://github.com/GoCarrot/teak-usage.git
  # Product Updates
  - url: https://github.com/GoCarrot/teak-usage.git
    start_path: newsletters
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
ui:
  bundle:
    # The first element of '.' is needed so that the rest of the path is evaluated from
    # the location of the playbook yml. This way it will work if invoked from either
    # the playbook path, or the project root path.
    url: ./../build/ui-bundle.zip
  supplemental_files: ./supplemental-ui

asciidoc:
  extensions:
  - ./lib/doxygen2adoc

  attributes:
    page-reference-sort-order: '!ROOT, !usage, unity, ios, android, server-api, !newsletters, *'
    page-base-nav-sort-order: 'ROOT, usage'
    page-sdk-nav-sort-order: 'unity, ios, android, server-api'
    linkattrs: ''
    experimental: ''
    doxygen2adoc:
    - symbols:
      - ./../../teak-unity/docs/symbolMap.json
      - ./../../teak-android/docs/symbolMap.json
      - ./../../teak-ios/docs/symbolMap.json
      verbose: false
      strict: false
