site:
  title: Teak Documentation
  url: https://docs.gocarrot-dev.com/
  start_page: sdk-reference::index.adoc
content:
  sources:
  - url: ./../../teak-unity
    start_path: docs
  - url: ./../../teak-sdk-reference
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
ui:
  bundle:
    # The first element of '.' is needed so that the rest of the path is evaluated from
    # the location of the playbook yml. This way it will work if invoked from either
    # the playbook path, or the project root path.
    url: ./../build/ui-bundle.zip
  supplemental_files: ./supplemental-ui
