version: 2.1

orbs:
  teak: teak/sdk-utils@0.0.10

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Build UI Bundle
          command: gulp bundle
workflows:
  version: 2

  bundle:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
