version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Build UI Bundle
          command: npx gulp bundle
      - persist_to_workspace:
          root: .
          paths:
            - build/ui-bundle.zip

  deploy_stage:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Upload UI Bundle to Stage
          command: sha512sum build/ui-bundle.zip
      - build_antora_playbook

workflows:
  version: 2

  bundle:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - deploy_stage:
          context: Antora
          requires:
            - build
          filters:
            tags:
              ignore: /.*/

commands:
  #
  # Trigger a playbook build
  #
  build_antora_playbook:
    description: "Trigger Antora Playbook Build"
    # parameters:
    #   live:
    #     type: boolean
    #     default: false
    steps:
      - run:
          name: Trigger Antora Playbook Build
          command: curl --location --request POST 'https://circleci.com/api/v2/project/github/GoCarrot/antora-playbook/pipeline' \
                    --header 'Content-Type: application/json' \
                    -u "${CIRCLE_API_TOKEN}"
