
= Getting Started

Getting up and running with Teak is easy, and we're going to help you keep it easy by giving you an overview of everything you'll need to plan tasks, and talk to the people who have what you need.

[NOTE]
.Quick Start
====
If you're a developer tasked with integrating Teak you can get started here: xref:developers.adoc[Teak for Developers]

If you're looking for how to use the product once it's integrated, start here: xref:usage::page$index.adoc[Teak for Marketing]
====

== Assumptions

We're making some assumptions in this doc, so we'll put them right up front:

* You're integrating Teak in a title you work on
* You want to get a clear idea of what integrating Teak will look like
* There is more than one person that needs to be involved in the integration process

== Before You Start

Sometimes the hardest task is getting all of the right people in the room together. Here's a list of what you're going to need for _complete_ integration with Teak, in rough order of importance.

* <<SDK Integration>>
* <<Push Credentials>>
* <<Server-to-server Reward Integration>>

== SDK Integration

In order to complete SDK integration, you will need:

* A developer who can build and test your game

SDK integration is a client developer task that can be accomplished and confirmed without too much work.

A developer-focused guide to integration is located at xref:developers.adoc[Teak for Developers].

include::partial$push-credentials.adoc[leveloffset=+1]

== Server-to-server Reward Integration

In order to complete server-to-server reward integration, you will need:

* A developer who can create an endpoint reachable by the Teak servers

Follow these instructions to implement the server-to-server reward endpoint: xref:server-api::page$rewards/endpoint.adoc[Teak Reward Endpoint].
