#!/usr/bin/env bash

set -eo pipefail

circle_token=$(cat ~/.circleci/cli.yml | grep -e '^token: .*$' | sed -nE 's/^token: (.*)/\1/p')
curl --request POST --url https://circleci.com/api/v2/project/github/GoCarrot/antora-ui-teak/pipeline \
     --header "Circle-Token: ${circle_token}" --header 'content-type: application/json' \
     --data '{"parameters":{"build_type":"production"}}'
