#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const YAML = require('yaml');
const { exec } = require('child_process');

const playbook_filename = path.join(__dirname, '..', 'playbook', 'antora-playbook-dev.yml');
const playbook = YAML.parse(fs.readFileSync(playbook_filename, 'utf-8'));

playbook.content.sources.forEach((source) => {
  const repo = path.join(__dirname, '..', 'playbook', source.url);
  const cmd = `(cd ${repo} && git pull)`;

  exec(cmd, (error, stdout, stderr) => {
    console.log(`> ${cmd}`);
    if (error) {
        console.error(error.message);
        return;
    }
    if (stderr) {
        console.error(stderr);
        return;
    }
    console.log(stdout);
  });
});
